repos:
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.2.2
    hooks:
      - id: gdformat
        name: gdformat
        description: Format GDScript files
        types: [file]
        files: \.(gd)$
        exclude: ^addons/
      - id: gdlint
        name: gdlint
        description: Lint GDScript files
        types: [file]
        files: \.(gd)$
        exclude: ^addons/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (^addons/|\.(gd|tscn|tres)$)
      - id: end-of-file-fixer
        exclude: (^addons/|\.(tscn|tres)$)
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
